name: Build Reseek

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-22.04
            build-system: cmake
            arch: x86_64
            cc: gcc-11
            cxx: g++-11
          - os: ubuntu-22.04
            build-system: makefile
            arch: x86_64
            cc: gcc-11
            cxx: g++-11
          - os: ubuntu-20.04
            build-system: cmake
            arch: x86_64
            cc: clang-12
            cxx: clang++-12

          # macOS builds
          - os: macos-13
            build-system: cmake
            arch: x86_64
            cc: clang
            cxx: clang++
          - os: macos-14
            build-system: cmake
            arch: arm64
            cc: clang
            cxx: clang++
          - os: macos-13
            build-system: makefile
            arch: x86_64
            cc: clang
            cxx: clang++

    runs-on: ${{ matrix.os }}

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          zlib1g-dev \
          pkg-config \
          ${{ matrix.cc }} \
          ${{ matrix.cxx }}

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install cmake zlib

    - name: Show build environment
      run: |
        echo "OS: $(uname -a)"
        echo "Compiler: ${{ matrix.cc }} / ${{ matrix.cxx }}"
        echo "Architecture: ${{ matrix.arch }}"
        echo "Build system: ${{ matrix.build-system }}"
        ${{ matrix.cc }} --version || true
        ${{ matrix.cxx }} --version || true
        cmake --version || true

    - name: Build with CMake
      if: matrix.build-system == 'cmake'
      run: |
        cd src
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)

    - name: Build with Makefile (Linux)
      if: matrix.build-system == 'makefile' && runner.os == 'Linux'
      run: |
        cd src
        make -f Makefile.generated clean || true
        make -f Makefile.generated -j$(nproc)

    - name: Build with Makefile (macOS)
      if: matrix.build-system == 'makefile' && runner.os == 'macOS'
      run: |
        cd src
        # Use the native build script for macOS
        chmod +x make_native.bash
        ./make_native.bash

    - name: Test executable (CMake)
      if: matrix.build-system == 'cmake'
      run: |
        if [ -f bin/reseek ]; then
          echo "Binary exists and is executable:"
          ls -la bin/reseek
          file bin/reseek
          ldd bin/reseek 2>/dev/null || otool -L bin/reseek 2>/dev/null || true
        else
          echo "Binary not found in expected location"
          find . -name "reseek" -type f 2>/dev/null || echo "No reseek binary found"
        fi

    - name: Test executable (Makefile)
      if: matrix.build-system == 'makefile'
      run: |
        if [ -f bin/reseek ]; then
          echo "Binary exists and is executable:"
          ls -la bin/reseek
          file bin/reseek
          ldd bin/reseek 2>/dev/null || otool -L bin/reseek 2>/dev/null || true
        else
          echo "Binary not found in expected location"
          find . -name "reseek" -type f 2>/dev/null || echo "No reseek binary found"
        fi

    - name: Run basic functionality test
      run: |
        if [ -f bin/reseek ]; then
          echo "Testing basic functionality..."
          ./bin/reseek --help || ./bin/reseek -h || echo "Help command not available"
          echo "Build completed successfully!"
        else
          echo "Cannot test - binary not found"
          exit 1
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: reseek-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.build-system }}
        path: |
          bin/reseek*
          src/build/reseek*
        retention-days: 30
        if-no-files-found: warn

  # Additional job for NEON-specific tests on ARM
  test-neon:
    runs-on: macos-14  # ARM64 runner
    needs: build
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build NEON tests
      run: |
        cd src
        # Compile the NEON test programs
        if [ -f simple_neon_test.cpp ]; then
          echo "Building NEON tests..."
          clang++ -std=c++11 -O3 -march=armv8-a+simd -D__ARM_NEON simple_neon_test.cpp -o simple_neon_test
          clang++ -std=c++11 -O3 -march=armv8-a+simd -D__ARM_NEON test_neon.cpp -o test_neon
          if [ -f raw_neon_test.cpp ]; then
            clang++ -std=c++11 -O3 -march=armv8-a+simd -D__ARM_NEON raw_neon_test.cpp -o raw_neon_test
          fi
        fi

    - name: Run NEON tests
      run: |
        cd src
        if [ -f simple_neon_test ]; then
          echo "Running simple NEON test..."
          ./simple_neon_test
        fi
        if [ -f test_neon ]; then
          echo "Running NEON test..."
          ./test_neon
        fi
        if [ -f raw_neon_test ]; then
          echo "Running raw NEON test..."
          ./raw_neon_test
        fi

  # Summary job
  build-summary:
    runs-on: ubuntu-latest
    needs: [build, test-neon]
    if: always()

    steps:
    - name: Build Summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Platform | Architecture | Build System | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|--------------|--------------|--------|" >> $GITHUB_STEP_SUMMARY
        if [ "${{ needs.build.result }}" == "success" ]; then
          echo "| Multi-platform | x86_64/ARM64 | CMake/Makefile | ✅ Success |" >> $GITHUB_STEP_SUMMARY
        else
          echo "| Multi-platform | x86_64/ARM64 | CMake/Makefile | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
        fi
        if [ "${{ needs.test-neon.result }}" == "success" ]; then
          echo "| ARM64 NEON | ARM64 | Tests | ✅ Success |" >> $GITHUB_STEP_SUMMARY
        elif [ "${{ needs.test-neon.result }}" == "failure" ]; then
          echo "| ARM64 NEON | ARM64 | Tests | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
        else
          echo "| ARM64 NEON | ARM64 | Tests | ⚠️ Skipped |" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Build artifacts are available for download from successful builds." >> $GITHUB_STEP_SUMMARY