name: Build Reseek

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-22.04
            arch: x86_64
            cc: gcc-11
            cxx: g++-11

          # macOS builds
          - os: macos-13
            arch: x86_64
            cc: clang
            cxx: clang++
          - os: macos-14
            arch: arm64
            cc: clang
            cxx: clang++

    runs-on: ${{ matrix.os }}

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          zlib1g-dev \
          pkg-config \
          ${{ matrix.cc }} \
          ${{ matrix.cxx }}

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install cmake zlib

    - name: Show build environment
      run: |
        echo "OS: $(uname -a)"
        echo "Compiler: ${{ matrix.cc }} / ${{ matrix.cxx }}"
        echo "Architecture: ${{ matrix.arch }}"
        ${{ matrix.cc }} --version || true
        ${{ matrix.cxx }} --version || true
        cmake --version || true

    - name: Build with CMake
      run: |
        cd src
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)

    - name: Test executable
      run: |
        if [ -f bin/reseek ]; then
          echo "Binary exists and is executable:"
          ls -la bin/reseek
          file bin/reseek
          ldd bin/reseek 2>/dev/null || otool -L bin/reseek 2>/dev/null || true
        else
          echo "Binary not found in expected location"
          find . -name "reseek" -type f 2>/dev/null || echo "No reseek binary found"
        fi

    - name: Run basic functionality test
      run: |
        if [ -f bin/reseek ]; then
          echo "Testing basic functionality..."
          ./bin/reseek --help || ./bin/reseek -h || echo "Help command not available"
          echo "Build completed successfully!"
        else
          echo "Cannot test - binary not found"
          exit 1
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: reseek-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          bin/reseek*
          src/build/reseek*
        retention-days: 30
        if-no-files-found: warn

  # Summary job
  build-summary:
    runs-on: ubuntu-latest
    needs: build
    if: always()

    steps:
    - name: Build Summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Platform | Architecture | Build System | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|--------------|--------------|--------|" >> $GITHUB_STEP_SUMMARY
        if [ "${{ needs.build.result }}" == "success" ]; then
          echo "| Multi-platform | x86_64/ARM64 | CMake | ✅ Success |" >> $GITHUB_STEP_SUMMARY
        else
          echo "| Multi-platform | x86_64/ARM64 | CMake | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Build artifacts are available for download from successful builds." >> $GITHUB_STEP_SUMMARY